name: Deploy Gacha

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/gacha/**' # INI BASED ON PATH CHANGES JADI NTAR KALAU ADA PUSH DIISNI OTOMATIS DEPLOY

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            if [ ! -d ~/imphnen-frontend-service-gacha ]; then
              git clone https://github.com/IMPHNEN/imphnen-frontend-service.git ~/imphnen-frontend-service-gacha
            else
              cd ~/imphnen-frontend-service-gacha && git fetch origin && git reset --hard origin/develop && git pull
            fi
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > ~/imphnen-frontend-service-gacha/apps/gacha/.env
            docker compose -f ~/imphnen-frontend-service-gacha/docker-compose-gacha.yml down || true
            docker compose -f ~/imphnen-frontend-service-gacha/docker-compose-gacha.yml build
            docker compose -f ~/imphnen-frontend-service-gacha/docker-compose-gacha.yml up -d
            docker image prune -af
